version: "3.8"

services:
  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL= http://backend:3001
    volumes:
      - ./Frontend:/app
    command: npm run dev
    env_file:
      - ./Frontend/.env.local

  backend:
    build: ./Backend/restaurante-api
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    volumes:
      - ./Backend/restaurante-api:/app
    command: node server.js

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
